:source-highlighter: highlight.js
= Ssh.NET.Instrumentation

Secure Shell Instrumentation Package for SSH.NET

[link=https://ci.appveyor.com/project/ThomasMaierhofer/ssh-net-instrumentation/branch/main]
image::https://ci.appveyor.com/api/projects/status/9m5vfq3ph4u3pv71/branch/main?svg=true[main Branch Build Status] 



== Executing Unit Tests and Integration Tests

=== Dockerfile

The folder test-ssh-server includes a Dockerfile with a SSH server and a dotnet SDK 3.1 installation.
This can be used to run the integration tests.

[source, docker]
----    
include::test-ssh-server/Dockerfile[]
----

== Executing the Integration Tests with the SSH Test Server

The test server image exposes the SSH port 22 which should be mapped to port 2222 and the 
current directory should be  mapped under /app in the docker container. 

=== Building and pushing the docker image to docker hub
There is a prebuilt docker image available "maierhoferconsulting/ssh-server-dotnet31-test".
These are the build / push commands for this image: 

[source, bash]
----
docker build -t maierhoferconsulting/ssh-server-dotnet31-test test-ssh-server
docker push maierhoferconsulting/ssh-server-dotnet31-test:latest
----

=== Running the prebuilt docker image in CI and on local machines

[source, bash]
----
docker run -d -v "$($pwd):/app" -p 2222:22 --name ssh_test maierhoferconsulting/ssh-server-dotnet31-test:latest
----

=== Running the unit tests and integration tests

[source, bash]
----
dotnet test src
----

=== Stopping and removing the docker container

[source, bash]
----
docker stop ssh_test
docker rm ssh_test
----

== Architecture Documentation

See link:doc/architecture.adoc[Architecture Documentation]
